apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::392935215471:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-0EWlE101oy5V
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::392935215471:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-21T19:05:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2307"
  uid: c217371a-6900-412b-8319-69eac6fdd0bf
